artifacts_root: artifacts

data:
  tic_list: ['SPY']
  interval: 1Day
  start_date: 2022-01-01
  end_date: 2022-12-31
  save_raw_data: True
  save_processed_data: True
  save_stream_data: True

  raw_data_file: artifacts/datasets/raw_data.csv
  processed_data_file: artifacts/datasets/processed_data.csv
  stream_data_file: artifacts/datasets/stream_data.csv

model:
  model_file: artifacts/trained_model/model.zip
  lookback: 30
  time_steps: 100000
  





