name: ai_trader

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  automated_trading:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/compose-action@v2

      # Step 3: Write .env file
      - name: Write .env file
        run: |
          echo "ALPACA_API_KEY=${ALPACA_API_KEY}" >> .env
          echo "ALPACA_SECRET_KEY=${ALPACA_API_SECRET}" >> .env
          echo "ALPACA_API_BASE_URL=${ALPACA_API_BASE_URL}" >> .env
          echo "ALPACA_PAPER=${ALPACA_PAPER}" >> .env

      # Step 4: Build and start Docker Compose services
      - name: Build and start Docker Compose
        run: |
          docker-compose up -d --build