name: ai_trader

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  automated_trading:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Write .env file
        run: |
          echo "ALPACA_API_KEY=${ALPACA_API_KEY}" >> .env
          echo "ALPACA_SECRET_KEY=${ALPACA_API_SECRET}" >> .env
          echo "ALPACA_API_BASE_URL=${ALPACA_API_BASE_URL}" >> .env
          echo "ALPACA_PAPER=${ALPACA_PAPER}" >> .env

      - name: Docker Compose Action
        uses: hoverkraft-tech/compose-action@v2.0.1
        run: |
          docker-compose up -d --build            
